namespace: dev
track: staging
replicaCount: 1
deploymentUrl: "publish.dev.buffer.com"
ingress:
  enabled: true
  path: /
  annotations:
    kubernetes.io/ingress.class: nginx
env:
  - name: API_ADDR
    value: https://k8s-api-php71-dev.buffer.com
