name: Cypress

on: [status]

jobs:
  cypress:
    name: "Cypress"
    runs-on: ubuntu-latest
    steps:    
    - name: Get Data
      uses: actions/github-script@0.8.0
      id: data
      with:
        script: |
          const { branches, context: statusContext, description, state, target_url } = context.payload;
          if (
            statusContext.startsWith("bufferbotbrains/cicd") &&
            state === "success" &&
            description.match(/Build successfully deployed/)
          ) {
            return { stagingUrl: target_url, branch: branches[0].name };
          }
          return false;
    
    - name: Log Results
      run: echo ${{ toJson(steps.data.outputs.result) }}
      
    - name: Bail out if not deployed status
      if: steps.data.outputs.result == 'false'
      run: exit 1
    
    - uses: actions/checkout@v2
      with:
        ref: ${{ steps.data.outputs.result.branch }}

    - name: Run Cypress
      uses: cypress-io/github-action@v1
      with:
        working-directory: e2e
        record: "true"
      env:
        CYPRESS_GITHUB_ACTIONS: "true"
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        CYPRESS_BASE_URL: ${{ steps.data.outputs.result.stagingUrl }}
        CYPRESS_PUBLISH_LOGIN_EMAIL: ${{ secrets.PUBLISH_LOGIN_EMAIL }}
        CYPRESS_PUBLISH_LOGIN_PASSWORD: ${{ secrets.PUBLISH_LOGIN_PASSWORD }}

        
