name: Cypress

on: [status]

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Get Staging URL
      uses: actions/github-script@0.8.0
      id: stagingUrl
      with:
        script: |
          const { context, description, state, target_url } = context.payload;
          if (
            context.startsWith("bufferbotbrains/cicd") &&
            state === "success" &&
            description.match(/Build successfully deployed/)
          ) {
            return target_url;
          }
          return false;
    
    - name: Log staging URL
      run: echo ${{ steps.stagingUrl.outputs.result }}
        
